name: Notion Daily Generator
on:
  schedule:
    - cron: "30 16 * * *" # 毎日 1 時 30 分(JST)に実行
  workflow_dispatch:
jobs:
  notion-daily-generator:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # - run: npm run lint
      - run: npm run deploy
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DIARY_DATABASE_ID: ${{ secrets.DIARY_DATABASE_ID }}
